os: osx
osx_image: xcode10.2

language: bash

git:
  # defines the depth of the github rep
  depth: false
  
install:
  # to show that we can run commands
  - whoami
  - echo "Start of pipeline"
  # not update the server
  - HOMEBREW_NO_AUTO_UPDATE=1
  
script:
  - ls
  - chmod +x hello.sh
  - ./hello.sh
  
after_script:
  - echo "End of pipeline"
